### ISSUE TITLE
MPD does not launch: error with libicui18n

### ISSUE THREAD

**Issue by AsbjornOlling** [archphile/packages#7]
Launching mpd gives me the error: 

```
$ mpd
mpd: error while loading shared libraries: libicui18n.so.61: cannot open shared object file: No such file or directory
```

I think this worked fine with the latest image that I downloaded, but has broken since a full system update.

Installed version of mpd-archphile is `0.20.20-2`

**Comment by archphile** [comment]
Hi,
What happened is completely normal. If you know how to do it , you will need to build all my custom packages again.

To sum up: Archphile is not a rolling release distro and you should not update the OS. It is also stated on the manual:

**Comment by AsbjornOlling** [comment]
Ah fair enough, I guess I didn't RTFM and updated the OS out of habit ;)

Thanks for the impressively fast (possible scripted?) reply.

**Comment by archphile** [comment]
Hi,
it's very common for people familiar with Arch, to update and break the OS. If I had the time to constantly be building and updating Archphile packages, Archphile could be a rolling release distro.

Unfortunately, this is something that I can't do (and never did).

BTW, if you are familiar with pkg building you can either rebuild to meet current dependencies, or you can edit the mirrorlist file, enable the first line, which is the rollback machine at the date of the creation of the image, and download base-devel and all other dependencies in order to build newer versions of archphile packages, with older versions of libraries etc.
